# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "76172c76eb19d1e9036d4bdcd8f9049f"
name = "product-discount-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "diegocheckout.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts, read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
